version: '3'
services:
  app:
    build: .
    command: bin/rails server --binding 0.0.0.0 --port 3000
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      TWITTER_API_KEY: ${TWITTER_API_KEY}
      TWITTER_API_SECRET: ${TWITTER_API_SECRET}
  db:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: pgpassword
